### PR TITLE
Resolve 5 resizable box

### PR DESCRIPTION
**Pull request by carueda**
I think this is now in good shape for a review.

Demo Video:  https://youtu.be/z_2SEMI9oIc

To edit an existing box:

- select the associated annotation on VARS  (or oryx)
- the box gets selected on Cthulhu  (yellow color)
- (A just added box gets selected immediately)
- click within the Cthulhu video area so it has focus for key events and type `E`
- this starts the editing mode; small red circles on the corners of the selected box will be shown
- drag any of these circles to resize the box
- An `Esc` or `Space bar` keystroke will cancel the ongoing editing
- upon releasing the mouse, the update takes place: this is, a removal of the "old" annotation, and the addition of a new one with the updated box
- type `E` again for any further edits
- rinse and repeat

### CODE REVIEW

**Comment by carueda** [comment]
However, this seems to be exposing an issue in VARS as the removed localizations upon the edits don't seems to get properly reflected there.

**Comment by carueda** [comment]
@hohonuuli  I've been adding also the ability to move the box around (while also doing some other refinements).

**Comment by carueda** [comment]
OK, much better now, and also including repositioning of the box:

- when in editing mode (upon pressing `E`), just press mouse inside the box and start dragging to reposition the whole box.
- the box is constrained to remain within the video view

Demo:   https://youtu.be/RskpJ-L6XrE

**Comment by hohonuuli** [comment]
@carueda Thanks for the updates. I'm hoping to review this later today.

**Comment by carueda** [comment]
BTW, as indicated in that recent commit, I just added the ability to remove the box being edited (via Shift-DELETE), mainly as a way to test the removal request itself (not in combination with any subsequent addition like in a normal edit), which, as mentioned previously, seems not to be properly handled on the VARS side.

As also mentioned before, the key call here is `application().localization().removeLocalization(id)` which is a method in the vcr4j-sharktopoda-client library.  My assumption has been that such call should take care of propagating the removal request.

**Comment by carueda** [comment]
sharktopoda seems to be doing its part:

```
DEBUG o.m.v.sharktopoda.client.localization.IO | Publishing to 'localization':
{"action":"remove","localizations":[{"localizationUuid":"209ca3bf-4630-4134-993b-a3410f4d6c4a"}]}
```

**Comment by carueda** [comment]
oryx does perform the requested removal:  https://www.screencast.com/t/h2AQVEzLm0x

**Comment by hohonuuli** [comment]
@carueda Looks good Carlos.

**Pull request merged**
